services:
  - type: web
    name: resume-ai-agent-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    rootDir: Backend
